---

- name: download kindlegen
  get_url:
    url: "http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v{{ kindlegen_version }}.tar.gz"
    dest: "{{ calibre_home }}/kindlegen_{{ kindlegen_version }}.tar.gz"
    checksum: sha512:5bd4928785ee06d92de1991a34029ffe343c087b4311f52c83df8d821d826b2e42f29e3047c0536140457fd478d300f621648f9eaef3a6568431a791e8147937
  notify: Install kindlegen

- name: directories
  file:
    path: "{{ calibre_home }}{{ item }}"
    state: directory
    owner: "{{ calibre_user }}"
    group: "{{ calibre_group }}"
  with_items:
    - /web/vendor
    - /kindlegen
